name: basket-api-build

on:
  push:
    paths: 
    - 'src/Services/Basket/**'    
    branches: [ feature/enable-github-actions, dev ]    

  pull_request:
    paths: 
    - 'src/Services/Basket/**'
    branches: [ feature/enable-github-actions ]          

env:
    
  APP_NAME: eshop
  API_NAME: basket.api
  SERVICE_NAME: basket-api
  TAG_NAME: linux-latest

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

    - name: Get code from the repo
      uses: actions/checkout@v2      

    - name: Build eShop basket.api docker image.
      run: |
        docker-compose -f src/docker-compose.yml build ${{ env.SERVICE_NAME }}

  push_to_registry:    
    name: Push basket-api docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check out the repo
        uses: actions/checkout@v2      
      
      - name: Build eShop basket.api docker image.
        run: |
          docker-compose -f src/docker-compose.yml build ${{ env.SERVICE_NAME }}
      
      - name: Re-tag the docker image
        run: |
          docker image tag ${{ env.APP_NAME }}/${{ env.API_NAME }}:${{ env.TAG_NAME }}  ${{ secrets.DOCKER_REPOSITORY_NAME }}/${{ env.API_NAME }}:${{ env.TAG_NAME }}

      - name: Push eShop basket.api docker image
        run: | 
          docker push ${{ secrets.DOCKER_REPOSITORY_NAME }}/${{ env.API_NAME }}:${{ env.TAG_NAME }}