name: catalog-api-build

on:
  push:    
    branches: [ feature/enable-github-actions, dev ]    

  pull_request:
    paths: 
    - 'src/Services/Catalog/**'
    branches: [ feature/enable-github-actions ]          

env:  
  DOCKER_REGISTRY_NAME: docker.pkg.github.com
  REPOSITORY_NAME: eshop
  SERVICE_NAME: catalog-api           
  TAG_NAME: linux-latest

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:

    - name: Get code from the repo
      uses: actions/checkout@v2      

    - name: Build eShop catalog.api docker image.
      run: |
        docker-compose -f src/docker-compose.yml build ${{ env.SERVICE_NAME }}

  push_to_registry:    
    name: Push catalog-api docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_NAME }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out the repo
      uses: actions/checkout@v2      

    - name: Build eShop catalog.api docker image.
      run: |
        docker-compose -f src/docker-compose.yml build ${{ env.SERVICE_NAME }}

    - name: Re-tag the docker image
      run: |
        docker image tag ${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG_NAME }}  ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG_NAME }}

    - name: Push eShop catalog.api docker image
      run: | 
        docker push ${{ env.DOCKER_REGISTRY_NAME }}/${{ env.REPOSITORY_NAME }}/${{ env.SERVICE_NAME }}:${{ env.TAG_NAME }}
