name: eShop catalog.api build

on:
  pull_request:
    paths: 
    - 'src/Services/Catalog/**'
    branches: [ feature/enable-github-actions ]          

env:
  IMAGE_NAME: catalog.api
  TAG: linux-latest
  CONTEXT_PATH: src
  DOCKER_FILE_PATH: src/Services/Catalog/Catalog.API/Dockerfile    

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:

    - name: Get code from the repo
      uses: actions/checkout@v1      

    - name: Build Docker images
      uses: docker/setup-buildx-action@v1
      with:                
        path:  ${{ env.CONTEXT_PATH }}
        dockerfile: ${{ format('{0}/{1}', env.CONTEXT_PATH , env.DOCKER_FILE_PATH ) }}
        repository:  ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAG }}     