name: catalog-api-build

on:
  pull_request:
    paths: 
    - 'src/Services/Catalog/**'
    branches: [ feature/enable-github-actions ]          

env:
  SERVICE_NAME: catalog-api           

jobs:

  build-docker-image:
    runs-on: ubuntu-latest
    steps:

    - name: Get code from the repo
      uses: actions/checkout@v1      

    - name: Build eShop catalog.api docker image.
      run: |
        docker-compose -f src/docker-compose.yml build ${{ env.SERVICE_NAME }}